[package]
name = "gravity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayfire = "3.8.0"
crossterm = "0.28.1"
lazy_static = "1.5.0"
ratatui = "0.28.0"
