[package]
name = "gravity"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayfire = "3.8.0"
crossterm = "0.28.1"
lazy_static = "1.5.0"
nalgebra = "0.33.0"
ratatui = "0.28.0"
serde_json = "1.0.127"
